### ISSUE TITLE
wifi connection without midea app?

### ISSUE THREAD

**Issue by marvinhinz** [mac-zhou/midea-msmart#16]
Hi,

first, thank you for this project. Im really looking into integrating this into my openhab. 
I havent mounted the ac yet, so im not familiar with the setup yet. 

When using the midea cloud app, you connect to the access point of the wifi module first and then setup your home wifi name and password, so the wifi module can connect to the local network.

Is this step needed too, when using this method? I'd like to skip the cloud completely :)

**Comment by 0xbw** [comment]
yes, need this step.
maybe skip cloud will to be a premium paid feature😄
