### ISSUE TITLE
refresh works but apply command don't

### ISSUE THREAD

**Issue by sergio49** [mac-zhou/midea-msmart#2]
Hi,
I'm in France, and I discovered your update yesterday. Nice job !!
I love the local connection (whithout cloud), I dream of it since 2 years :)
I have a Qlima AC (midea built). The code works well for refresh data (get state and parameters from AC), but applying new values only works 1 of 10 times or less... don't know why. I try to put prints but can't see anything. (Ido not user Home assistant, just send orders directly with python)
for example here an exchenge between my webserver and the AC :

Finalize request data: aa23ac000000000000024081426503ff000000000000000000000000000000000000bc09
Recieved from 3c4c0000000f: aa22ac00000000000302c00043287f7f00300000005f5a000000000000000000000e0d
Appliance response data: c00043287f7f00300000005f5a000000000000000000000e0d

I don't know if it can help...
Thanks

**Comment by 0xbw** [comment]
this looks ok.
How long are you operating the air conditioner at intervals?
Not too frequently.

**Comment by sergio49** [comment]
Hi, 
It works well now, I think I operated my device too frequently during my tests. In "normal" use case, it works perfectly on local connection and far more quickly than passing thrugh the cloud like before.
Thank you  very much
