### ISSUE TITLE
Mider AC not supported

### ISSUE THREAD

**Issue by PatMei** [mac-zhou/midea-msmart#20]
Hello,

sadly, my ac of midea isn't supported via your midea-msmart.
Logging infos:

------------------------

pi@raspberrypi:~ $ midea-discover
INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.1.20
INFO:msmart.cli:Discovering devices with UDP Broadcast, press CTRL-C to quit...
INFO:msmart.cli:Midea Local Data 192.168.2.15 837000b8200f04015a5a0111a8007a80000000000000000000000000534a000000130000000000000000000000000000c9dba42446780e89ca2989f876df6a55858af37fdb1aa402d4a5addbb7f5e4466921d8ad922d2805f1f9f9b3d78568d381cea6223c7417895adabd0b1d20bd0f45aa229ad5d70ede5de8aa75aab124a5ea299df42bb39faf330f5ff8c078f38ef31443d17c3aac03a7656614ae1dca44fd21ad9c2af4841039f0f4be5e90c31134481db8d1ef2de31cb993c2f253b33d
DEBUG:msmart.packet_builder:Finalize request data: aa20ac00000000000003418100ff03ff0002000000000000000000000000246ddb
DEBUG:msmart.lan:Sending to 192.168.2.15:6444 5a5a011168002000000000001e24031408071414534a0000001300000000000000000000000000006b000a76e27eed2c3647e57d8602df8b5e715882de60dba0e3796fe854da3af32d7ed3293c5031048410429ad538d2fbaa83339460bcb3449c04e26668216aeb
INFO:msmart.lan:Couldn't connect with Device 192.168.2.15:6444
DEBUG:msmart.device:refresh - Recieved from 192.168.2.15, 534a00000013:
INFO:msmart.cli:*** Found a unsupported '0xac' at 192.168.2.15 - id: 20890720946771 - sn: P0000000Q1847C9BBE52200000 - ssid: net_ac_5220

-----------------------

Maybe you could help me to get this supported ;) Please let me know, whether you need more infos (and which/how).

Cheers,
PatMei

**Comment by 0xbw** [comment]
I am trying to support.
I created a telegram group https://t.me/joinchat/BhU6LRytPXLsiqTIar0jqg <https://t.me/joinchat/BhU6LRytPXLsiqTIar0jqg>, you can join.

**Comment by demichve** [comment]
Hi,
I have the same issue. Using the Midea App, I can control my AC. I even could update the Firmware using WAN, recently.
But using this script I get „ Found a unsupported '0xac ...“

Is there any solution?

Michael

**Comment by sergiomfsilva** [comment]
Hi,

How can I help with this? 

I have SmartKey EU-OSK 103 and with that SmartKey I has the issues described but if I use a OSK102 on the same machine all the code works well. 

What are the procedures to catch the require information?

Best Regards

**Comment by hubertverstraete** [comment]
Hi
Same issue with a 8370 midea device. Let me know how I can help.
Regards,

**Comment by Lumpusz** [comment]
Hi same issue here with a 8730 midea ac with OSK103 SmartKey. How I can help?

**Comment by asabino** [comment]
Hi,
Same here using CE-SK103... Joining telegram so I can (try to) help.

**Comment by njordan77** [comment]
is there a fix already? 
not sure what this repository means....looks the same but writes that 0xac is fixed...but how to install/try if its the same installer pip3 install msmart ?

Cheers

**Comment by chicxurug** [comment]
Same issue with Midea MG2X-12-SP Xtreme Save. Can you add this to the list of devices to be supported? Also, let me know if I can help in the implementation. See midea-discover output:

INFO:msmart.cli:msmart version: 0.1.24
INFO:msmart.cli:Sending Device Scan Broadcast...
INFO:msmart.cli:Midea Local Data 192.168.0.173 837000b8200f045d5a5a0111a8007a80000000000000000000000000dd770200001d0000000000000000000000000000e71d3367e29180cb520638955c9569feeaae5899cd67f6da1bf0a5639590e1e3fe254618fa9b19bfa9345707ca3bb1af31ef3f0a763ad264d93f82a08812799e9f559ce15ed6ce9162a8e03adaabaf971fca94541303884c52e880ddefc03190f31443d17c3aac03a7656614ae1dca44f936d67bba5ff479b46e35fd158f216c58e3524860337d594fc99eb8776d9df1
INFO:msmart.cli:Decrypt Reply: 192.168.0.173 ad00a8c02c19000030303030303050303030303030305131334332303933384543413239303030300b6e65745f61635f434132390000000001000000040000000000ac000000000000003c20938eca29069fcd0300080103000000000000000000000000000000000000000000
INFO:msmart.lan:Couldn't connect with Device 192.168.0.173:6444
INFO:msmart.cli:*** Found a unsupported device - type: '0xac' - version: V3 - ip: 192.168.0.173 - port: 6444 - id: XXXomittedXXX - sn: XXXomittedXXX - ssid: XXXomittedXXX

**Comment by 0xbw** [comment]
The new version already supports 8370. Please Try.
