### ISSUE TITLE
UART protocol

### ISSUE THREAD

**Issue by dudanov** [mac-zhou/midea-msmart#22]
Hi. Help is needed!

The fact is that I have an Electrolux air conditioner. Externally, the control boards are identical and many sources claim that they are manufactured in the Midea factories in China. Specifically for my model, the "USB" module is not on sale in the Russian market, although the connector is provided and declared by the supplier (sometimes it happens)... Therefore, it is not possible to carry out reverse engineering. If I knew the protocol on the UART side, I could at least try to control the device. It is necessary to help understand the relationship between the external control protocol and frames on the side of the UART interface.

Perhaps, with your help, community will get a library for controlling Midea and Electrolux air conditioners by UART interface.

I would be grateful for the help provided. Thanks.

**Comment by dlobato** [comment]
Hi @dudanov,

I'm implementing a protocol decoder for sigrok here: https://github.com/dlobato/sigrok-midea-serial-decoder
It's far from complete, I'm slowly filling the gaps. Maybe it helps you once you connect to the uart port.

**Comment by dudanov** [comment]
Hi, @dlobato 

Thanks for reply. I'll see and try.

I'll tell you more about my air conditioner. In my case, the WIFI dongle (which is not available for sale) is connected to the display board. It is controlled by the Sinowealth SH79F1612AM microcontroller with two UART interfaces, one of which is connected to the main control board, the other to the WIFI dongle.

UPD: UART config between mainboard is: 2400/8N1, between WIFI dongle is unknown.

How is this implemented in Midea air conditioners?

**Comment by dlobato** [comment]
In my case we bought the dongle (CE-SK103) as an extra to add wifi connectivity. Dongle is connected to a board as seen here: 
![IMG_20200529_112350](https://user-images.githubusercontent.com/1379455/89523929-97094c00-d7db-11ea-9f65-368076d52552.jpg)

The dongle has a usb connector, but actually is using the data pins as TX/RX. The UART configuration is 9600/8N1.

The decoder is based on the information found on this document: http://chipsc.com/home/views/default/resource/images/111.pdf

**Comment by dudanov** [comment]
Thanks for photo.

I understand that your principle is the same: the display unit has 2 UART interfaces, one (on the left in the photo) goes to the main control board, and the second to the WIFI dongle.

Have you examined the protocol between the main board and the display unit?

**Comment by dudanov** [comment]
It's worked! Thanks, @dlobato and community!
I haven't tested the command messages yet, but I think everything will work, protocol is same!
Here is also a photo of my display board and air conditioner model: **Electrolux EACS/I-09HAT/N3**.

![01](https://user-images.githubusercontent.com/10439739/89541459-71963580-d80f-11ea-9fcf-0372bc869266.png)
![2020-08-06 18-13-31](https://user-images.githubusercontent.com/10439739/89542647-fc2b6480-d810-11ea-9ffb-70dab1066660.png)
