### ISSUE TITLE
Display command

### ISSUE THREAD

**Issue by dudanov** [mac-zhou/midea-msmart#24]
Hi everyone.

Once they have already helped me a lot in #22  about the UART protocol. Thank you so much.
I figured out all the necessary commands for my air conditioner except _**enabling / disabling the LED display**_.
There is a similar command in the [original code](https://github.com/mac-zhou/midea-msmart/blob/19eb28ea007cffc129ef8d971b5f61404880b08b/msmart/command.py#L156), but doesn't work for me.
Based on the packet headers, protocol version 3 is used.

Can anyone help with this question? Thanks.

**Comment by reneklootwijk** [comment]
On my unit enabling/disabling the LED also does not work. The official Midea Air app also does not show the option, while for other units, the app does show the option to disable the LED light. Apparantly, not all units expose the ability to disable the LED via the UART protocol. I am not exactly clear what capability returned in the response to the B5 command reflects this.

**Comment by 0xbw** [comment]
you can find any command from this file [0xAC.zip](https://github.com/mac-zhou/midea-msmart/blob/master/0xAC.zip)
