### ISSUE TITLE
非常希望能加入华菱空调的支持。同样用的是美居APP。同样6444端口开放

### ISSUE THREAD

**Issue by boyyao** [mac-zhou/midea-msmart#3]
非常非常期待能帮助解密华菱的协议。不知道是单独一套加密方案还是只是控制命令的区别。ha中提示是timeout。。如果可以我可以全程提供外网的6444端口映射和美居app账号供观察。以及协助抓包。。

**Comment by 0xbw** [comment]
将msmart升级到0.1.16 然后运行```midea-discover -d``
然后在这里贴出输出 或许我可以解决

**Comment by 0xbw** [comment]
此问题超过2周未得到答复
