### ISSUE TITLE
Update 0.1.23 -> 0.1.24 stops the integration from working

### ISSUE THREAD

**Issue by EliotWalker** [mac-zhou/midea-msmart#30]
I had two air con units showing up in home assistant in version 0.1.23 however after performing the update they are now showing as unavailable. I am using version 2020.11.0 of home assistant on a Raspberry Pi 3.

To try and fix the issue I have rebooted the Pi, power cycled the air con, uninstalled the integration and reinstalled it.

The only thing I can find in the log is: Update of climate.midea_ac_0*********1 is taking over 10 seconds 
(* to hide the item number)

**Comment by asabino** [comment]
Same issue here, since the update the AC units are unavailable.

**Comment by 0xbw** [comment]
Need a more detailed log
