### ISSUE TITLE
V3 protocol support

### ISSUE THREAD

**Issue by g199209** [mac-zhou/midea-msmart#31]
Do you plan to support v3 control protocol in the future?

-------

未来是否计划支持 v3 控制协议？试了一下我已有的新风机用的是 v3 协议的。

```
Found a unsupported device - type: '0xce' - version: V3 - ip: 10.42.240.134 - port: 6444
```

**Comment by georgezhao2010** [comment]
take a look
https://github.com/mac-zhou/midea-msmart/issues/15#issuecomment-734136201

**Comment by g199209** [comment]
> take a look
> [#15 (comment)](https://github.com/mac-zhou/midea-msmart/issues/15#issuecomment-734136201)

Thanks~
