### ISSUE TITLE
Discover don't work

### ISSUE THREAD

**Issue by saper-2** [mac-zhou/midea-msmart#34]
Hello,

I have Midea AC (rebranded by Rotenso and app that is recommended by them: NetHome Plus - it work ok) , the dongle I have is:  ```EU-OSK 103``` .

Unfortunately discover don't find my AC at all 😢 , here is output:
```
pi@raspberrypi:~/midea/midea-msmart $ ./discover.py -d
INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.1.24
INFO:msmart.cli:Sending Device Scan Broadcast...
pi@raspberrypi:~/midea/midea-msmart $
``` 

Since I know the IP that it gets from DHCP server I wanted to try "example" (just reading part for reading info) but I have no idea how to get the device_id . I do have the QR code in "human text format" (it's just some link with code - the code is 22 char long: 10 first chars is some number starting with "P" letter, last 12 chars is MAC address of wifi dongle) - it's possible to extract the device ID from that code - how long it should be? I also missing communication port (looking at code, seems it's "random" 🤔 , but I think by the morning I should know which are ports open 😅  ... nmap 💪 -> found: 6444/tcp port open only).
 

The ```discover.py``` script (I have written it because I did not want to install another python package):
```
#!/usr/bin/python3
import msmart.cli
msmart.cli.discover()
```

**Comment by 0xbw** [comment]
try new version and open debug

**Comment by Rivka92** [comment]
also for me it does not work.

**Comment by Rivka92** [comment]
[midea.log](https://github.com/mac-zhou/midea-msmart/files/6995940/midea.log)
debugged using LD_DEBUG on archlinux

**Comment by 0xbw** [comment]
It is recommended to run on other devices to see

**Comment by Rivka92** [comment]
> It is recommended to run on other devices to see

it's unclear

**Comment by 0xbw** [comment]
> > It is recommended to run on other devices to see
> 
> it's unclear

try to run this script on other machine

**Comment by josemlopes** [comment]
Hello,

I have 2 Midea AC rebranded with dongles OSK101 working fine with  MSmart and Midea Smart IOS Apps but running the script I don´t have the desirable Device ID

C:\Users\JLopes>midea-discover
INFO:msmart.cli:msmart version: 0.1.29
INFO:msmart.cli:Sending Device Scan Broadcast...
Traceback (most recent call last):
  File "d:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python39\Scripts\midea-discover.exe\__main__.py", line 7, in <module>
  File "d:\program files\python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "d:\program files\python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "d:\program files\python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\program files\python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "d:\program files\python39\lib\site-packages\msmart\cli.py", line 134, in discover
    response = get_device_info(m_ip, int(m_port))
  File "d:\program files\python39\lib\site-packages\msmart\cli.py", line 170, in get_device_info
    sock.sendall(message)
NameError: name 'message' is not defined

**Comment by 0xbw** [comment]
your deive is V1
please join telegram group and contact me.
https://t.me/joinchat/UFSSaqBJE5RqvSOq

**Comment by 0xbw** [comment]
No reply for a long time, close
