### ISSUE TITLE
SK102 wifi usb key goes unavailable for 30 minutes after 12 state queries

### ISSUE THREAD

**Issue by fpoms** [mac-zhou/midea-msmart#36]
I have a Klimaire AC unit with an SK102 wifi usb key installed in it to support WIFI access. I've found that when the unit is queried 12 times (12 requests for the unit's state) it goes offline and won't respond to requests for 30 minutes. After 30 minutes, it resumes normal operation. 

It doesn't seem to matter what interval this occurs in. If I query the state every 15 seconds, it goes down after 3 minutes. If I query every 5 minutes, it goes down after 1 hour.

This doesn't seem to be a problem with the unit itself because when I use the official Midea Air app it is able to issue many state updates and refreshes without this issue occurring. I imagine there is something about how the data packets are being sent to the WIFI key that is causing this issue.

Let me know if I can provide more info.

**Comment by rokam** [comment]
This seam to be the same as #30

**Comment by 0xbw** [comment]
Commands may not be compatible with your device.
You need to grab packets on the phone and device, and send to me.

**Comment by 0xbw** [comment]
You did not provide a more detailed log, so close this issue
