### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by chicxurug** [mac-zhou/midea-msmart#37]
In the example.py the port parameter is missing:

c = midea_device('YOUR_AC_IP', YOUR_AC_ID)

The port has no default value thus needs to be provided. Would be nice to see an actually working example or the port initialized with adefault one. What is the most common port for Midea AC?

**Comment by zvldz** [comment]
default port 6444

**Comment by chicxurug** [comment]
Thanks. It seems to send something on port 6444, but still get an error:
INFO:msmart.lan:Couldn't connect with Device 192.168.0.173:6444
Is it due to the AC is not supported (Midea Extreme Save)? Mobile app works fine.

**Comment by zxq432** [comment]
c = midea_device('YOUR_AC_IP', YOUR_A_ID, YOUR_AC_PORT)

**Comment by 0xbw** [comment]
you can use command  `midea-discover` to find `YOUR_AC_PORT`.
not surprisingly, it should be 6444.
if you see `Found a unsupported device`, you can't use this example.py

**Comment by zxq432** [comment]
midea_device fuction needs 3 args: midea_device(device_ip, device_id, device_port), the 3rd arg is needed.




, but the example.py only supplied 2 args: midea_device('YOUR_AC_IP', YOUR_AC_ID)




it is needed to make change to example.py from midea_device('YOUR_AC_IP', YOUR_AC_ID) to midea_device('YOUR_AC_IP', YOUR_AC_ID, 6444)




please check cli.py to verify it:

cli.py:from msmart.device import device as midea_device

cli.py:    _device = midea_device(device_ip, device_id, device_port)














--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Mac_Zhou  ***@***.***>
 

 
 发送时间: 2021-07-12 11:17:25
 

 
 收件人:mac-zhou/midea-msmart ***@***.***> 

 
 抄送:zxq432 ***@***.***>,Comment ***@***.***> 

 
 主题: Re: [mac-zhou/midea-msmart] Example does not work (#37)
 





 you can use command midea-discover to find YOUR_AC_PORT.
 not surprisingly, it should be 6444.
 if you see Found a unsupported device, you can't use this example.py

**Comment by 0xbw** [comment]
try new version

**Comment by 0xbw** [comment]
https://github.com/mac-zhou/midea-msmart/commit/48bd5b1c309a8eda7940f82c3e2840ffa9c757db
