### ISSUE TITLE
Min fan speed  patch

### ISSUE THREAD

**Issue by zxq432** [mac-zhou/midea-msmart#38]
patch.txt to add Min fan speed,
patch2.txt to fix example.py

[patch2.txt](https://github.com/mac-zhou/midea-msmart/files/6793081/patch2.txt)
[patch.txt](https://github.com/mac-zhou/midea-msmart/files/6793082/patch.txt)

**Comment by zxq432** [comment]
diff --git a/example.py b/example.py
index ad2e853..561ab9c 100644
--- a/example.py
+++ b/example.py
@@ -4,9 +4,9 @@ from msmart.device import air_conditioning_device as ac
 import logging
 logging.basicConfig(level=logging.DEBUG)

-# first take device's ip and id
+# first take device's ip, id and port
 # pip3 install msmart; midea-discover
-c = midea_device('YOUR_AC_IP', YOUR_AC_ID)
+c = midea_device('YOUR_AC_IP', YOUR_A_ID, YOUR_AC_PORT)
 device = c.setup()
 # Refresh the object with the actual state by querying it
 device.refresh()
@@ -29,6 +29,7 @@ print({
 device.power_state = True
 device.prompt_tone = False
 device.target_temperature = 25
+device.fan_speed = ac.fan_speed_enum.Min
 device.operational_mode = ac.operational_mode_enum.cool

 # commit the changes with apply()

**Comment by zxq432** [comment]
diff --git a/example.py b/example.py
index ad2e853..561ab9c 100644
--- a/example.py
+++ b/example.py
@@ -4,9 +4,9 @@ from msmart.device import air_conditioning_device as ac
 import logging
 logging.basicConfig(level=logging.DEBUG)

-# first take device's ip and id
+# first take device's ip, id and port
 # pip3 install msmart; midea-discover
-c = midea_device('YOUR_AC_IP', YOUR_AC_ID)
+c = midea_device('YOUR_AC_IP', YOUR_A_ID, YOUR_AC_PORT)
 device = c.setup()
 # Refresh the object with the actual state by querying it
 device.refresh()
@@ -29,6 +29,7 @@ print({
 device.power_state = True
 device.prompt_tone = False
 device.target_temperature = 25
+device.fan_speed = ac.fan_speed_enum.Min
 device.operational_mode = ac.operational_mode_enum.cool

 # commit the changes with apply()

**Comment by 0xbw** [comment]
you can PR, thanks
