### ISSUE TITLE
Login error during discovery when more than one AC is available

### ISSUE THREAD

**Issue by mkissjoe** [mac-zhou/midea-msmart#50]
Hi,

I tried to discover my AC units with this tool, but it did not succeed. Running in debug mode I saw that the script tries to  create multiple login sessions, this could be the problem. I got no error, when there is only one AC unit is available in the network.
[midea-discover.log](https://github.com/mac-zhou/midea-msmart/files/7146119/midea-discover.log)

**Comment by 0xbw** [comment]
i just updated，please try:
```shell
pip3 uninstall msmart
pip3 install git+https://github.com/mac-zhou/midea-msmart
```

**Comment by mkissjoe** [comment]
It is working great, thx for the quick fix!
