### ISSUE TITLE
Midea AC not discovered

### ISSUE THREAD

**Issue by impsik** [mac-zhou/midea-msmart#52]
I have Midea unit with EU-OSK 103 tongle. I also know IP address of the unit  but i'm not able to discover it.
I also scanned that IP address, but all ports, including UDP ports, are closed.
Midea Oasis, 2021 year model.
Output:
```
% midea-discover -a MY-EMAIL -p MY_PWD -d
INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.1.35 Currently only supports ac devices.
INFO:msmart.cli:Sending Device Scan Broadcast...
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:msmart.scanner:Broadcast message sent: 0
DEBUG:msmart.scanner:Socket timeout
```

**Comment by 0xbw** [comment]
update to new version 0.2.0 
you can try `midea-discover -a MY-EMAIL -p MY_PWD -i DEVICE_IP_ADDR`
