### ISSUE TITLE
error

### ISSUE THREAD

**Issue by howard999090** [mac-zhou/midea-msmart#64]
My terminal shows
![截屏2022-01-25 上午9 54 04](https://user-images.githubusercontent.com/98271458/150896237-6d8b7cd6-f6e9-445e-8db2-3bba1fa63a6f.png)
How can I solve that?

**Comment by tinymins** [comment]
Try this:

```
"$(which python | xargs dirname | sed -e 's/^.*=//g')/midea-discover"
```

The goal is find where `midea-discover` file is located, and exec it.

This is your machine python pip install problem. I think asking this kind of question here, the author may not want to answer it. :-)

**Comment by kingtao1024** [comment]
try reboot your computer~

**Comment by 0xbw** [comment]
try open a new terminal
