### ISSUE TITLE
Midea AC - Token reset?

### ISSUE THREAD

**Issue by andreasc1** [mac-zhou/midea-msmart#68]
hi dev, another issue i noticed is that every few weeks the integrated entities stop working, and after running midea-discover i see a different key and token. replacing them they work again.

is there a way to avoid the above?

**Comment by 0xbw** [comment]
no need to retrieve token and k1， token and k1 can reuse.
the reason for this should be `authentication failure` or `respone is ERROR`
The new version has fixed, please try new version
