### ISSUE TITLE
空调关机状态下室外温度102.5摄氏度 开机状态下正常，美居APP室外温度正常。

### ISSUE THREAD

**Issue by tataishan** [mac-zhou/midea-msmart#81]
midea-discover -d
INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.2.3 Currently only supports ac devices, only support MSmartHome APP.
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:msmart.scanner:Broadcast message sent: 1
DEBUG:msmart.scanner:Midea Local Data 192.168.100.198 5a5a011178007a800000000000000000000000005cd0070000050000000000000000000001000000e1e19daf32fd8265186ba4bde8ecf550bbb07f9ab11dbe08336f36209b9b42178a19dbba0dd6c43950c5b6b9d1c4bf901ec3809c88bc2dc8e76b0cdb5670f84647c88c4edf512f00c3df40d78ea500fd
DEBUG:msmart.scanner:Decrypt Reply: 192.168.100.198 c664a8c02c19000030303030303032313132323235303732353733303330374530333336303030300d6d696465615f61635f30333336
DEBUG:msmart.scanner:Socket timeout
DEBUG:msmart.command:Finalize request data: aa20ac00000000000003418100ff03ff000200000000000000000000000026d175
DEBUG:msmart.device.AC.appliance:pkt_builder: 192.168.100.198:6444 len: 104 data: 5a5a0111680020000000000057262409180616145cd00700000500000000000000000000000000006b000a76e27eed2c3647e57d8602df8b7760b65cc8abde8d47750695623f1296137efcc7f8fe55c6253e8dc10f59f57a3f318e797f7820f30bfd997110e9374d
DEBUG:msmart.lan:Attempting new connection to 192.168.100.198:6444
DEBUG:msmart.lan:Socket 192.168.100.105:56308 -> 192.168.100.198:6444 retries: 0 time: 0.0 tcp_key: None
DEBUG:msmart.lan:Sending 192.168.100.105:56308 -> 192.168.100.198:6444 retries: 0 time: 0.0 message: 5a5a0111680020000000000057262409180616145cd00700000500000000000000000000000000006b000a76e27eed2c3647e57d8602df8b7760b65cc8abde8d47750695623f1296137efcc7f8fe55c6253e8dc10f59f57a3f318e797f7820f30bfd997110e9374d
DEBUG:msmart.lan:Recv 192.168.100.105:56308 -> 192.168.100.198:6444 retries: 0 time: 1.03 Response: 5a5a0111680020800000000000000000000000005cd0070000050000000000000000000001000000c79bba0b770173bde2475b21410ed5ae63484720bc2c38f65a53aa7441499e054af27299fbf8f9a00cb0ccb09948f9aed7c222485afcf8ed78dca163f5f97e2d
DEBUG:msmart.lan:Get responses len: 104
DEBUG:msmart.device.AC.appliance:Got responses from 192.168.100.198:6444 Version: 2 Count: 1 Spend time: 1.04
DEBUG:msmart.device.AC.appliance:Update from 192.168.100.198:6444 aa21ac00000000000203c0004c147f7f00000000006cff100050000000000026130c
DEBUG:msmart.command:Appliance response data: c0004c147f7f00000000006cff100050000000000026130c
DEBUG:msmart.scanner:{'_name': None, '_lan_service': <msmart.lan.lan object at 0xffffaccac730>, '_ip': '192.168.100.198', '_id': 5497558650972, '_port': 6444, '_keep_last_known_online_state': False, '_type': 172, '_updating': False, '_defer_update': False, '_half_temp_step': False, '_support': True, '_online': True, '_active': True, '_protocol_version': 2, '_token': None, '_key': None, '_last_responses': [], '_prompt_tone': False, '_power_state': False, '_target_temperature': 28.0, '_operational_mode': <operational_mode_enum.cool: 2>, '_fan_speed': <fan_speed_enum.Silent: 20>, '_swing_mode': <swing_mode_enum.Off: 0>, '_eco_mode': False, '_turbo_mode': False, 'fahrenheit_unit': False, '_on_timer': {'status': False, 'hour': 31, 'minutes': 3}, '_off_timer': {'status': False, 'hour': 31, 'minutes': 3}, '_indoor_temperature': 29.0, '_outdoor_temperature': 102.5}
DEBUG:msmart.scanner:*** Found a device: {'name': 'midea_ac_0336', 'ssid': 'midea_ac_0336', 'ip': '192.168.100.198', 'port': 6444, 'id': 5497558650972, 'version': 2, 'token': None, 'key': None, 'type': 'ac', 'sn': '00021122250725730307E03360000', 'model': '50725', 'support': True, 'run_test': True}
INFO:msmart.cli:*** Found a device: {'name': 'midea_ac_0336', 'ssid': 'midea_ac_0336', 'ip': '192.168.100.198', 'port': 6444, 'id': 5497558650972, 'version': 2, 'token': None, 'key': None, 'type': 'ac', 'sn': '00021122250725730307E03360000', 'model': '50725', 'support': True, 'run_test': True}

**Comment by 0xbw** [comment]
这说明你的空调不支持户外温度 我有2款空调 一款支持 一款不支持
如果不支持，APP里的室外温度是显示的是 当天天气预报的温度
